### ISSUE TITLE
Passing Lists from Terraform outputs

### ISSUE THREAD

**Issue by rv-agelnar** [caltechads/deployfish#26]
Say we want to pass a list of subnets to a Fargate definition, currently we have to do
```hcl
output "subnet_1" {...}
output "subnet_2" {...}
output "subnet_3" {...}
```

```yml
services:
 - name: example
    vpc_configuration:
        subnets:
            ${terraform.subnet_1}
            ${terraform.subnet_2}
            ${terraform.subnet_3}
```

This means that you have to list them out. Can you do something like:

```hcl
output "app_subnet_ids" {
    value = ["list of subnet ids", ...]
}
```

```yml
services:
 - name: example
    vpc_configuration:
        subnets: ${terraform.app_subnet_ids}
```

And if not, would you consider this as a feature? Being able to pass lists directly from terraform outputs would make certain things really flexible.

My current application is that I'm trying to create a some terraform and deployfish config which can be deployed to any region, which means that we'll have varying numbers of AZs. I'd like to be AZ count agnostic, which we've achieved for our VPC/subnet setup.
